# Generated by Django 4.1.3 on 2022-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_login_wrong"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carname", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=20)),
                ("modelyear", models.IntegerField()),
            ],
        ),
    ]
