# Generated by Django 4.1.3 on 2022-11-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_cardetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardetails", old_name="carname", new_name="car_name",
        ),
        migrations.RenameField(
            model_name="cardetails", old_name="modelyear", new_name="model_year",
        ),
    ]
