# Generated by Django 4.1.3 on 2022-11-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_rename_carname_cardetails_car_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarPrice",
            fields=[
                (
                    "car_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="cars.cardetails",
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
    ]
