# Generated by Django 4.1.3 on 2022-11-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_carprice_car_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="carprice", name="car_name",),
    ]
